name: CI - Backend & Frontend Coverage
run-name: Backend & Frontend Coverage
on:
  workflow_call:


jobs:
  backend-tests:
    name: Tests backend (Java)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./back

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run tests with JaCoCo
        run: mvn clean verify

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: back/target/site/jacoco/

      - name: Upload backend classes
        uses: actions/upload-artifact@v4
        with:
          name: backend-classes
          path: back/target/classes
