name: CI - Coverage + Sonar
run-name: Coverage + Sonar Analysis

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  coverage-and-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # FRONTEND

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: front
        run: npm ci

      - name: Run frontend tests with coverage
        working-directory: front
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: Upload frontend coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: front/coverage/bobapp/

      # BACKEND

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build backend with tests
        working-directory: back
        run: mvn clean verify

      - name: Upload backend coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: back/target/site/jacoco/

      # SONAR

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.modules=back,front
            -Dback.sonar.sources=back/src/main/java
            -Dback.sonar.tests=back/src/test/java
            -Dback.sonar.java.binaries=back/target/classes
            -Dback.sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
            -Dfront.sonar.sources=front/src
            -Dfront.sonar.tests=front/src
            -Dfront.sonar.typescript.lcov.reportPaths=front/coverage/bobapp/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
