name: Orchestrator Workflow

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-ci-coverage:
    uses:  .github/workflows/ci-coverage.yml@main

  run-sonar-analysis:
    needs: run-ci-coverage
    uses:  .github/workflows/sonar-analysis.yml@main

  run-docker-publish:
    needs: run-sonar-analysis
    uses:  .github/workflows/docker-publish.yml@main
