name: Orchestrator Workflow

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-sonar-analysis:
    uses: ./.github/workflows/ci-coverage.yml


  run-docker-publish:
    needs: run-sonar-analysis
    uses: ./.github/workflows/ci-coverage.yml
