name: Orchestrator Workflow

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-ci-coverage:
    uses: ./.github/workflows/ci-coverage.yml

  run-sonar-analysis:
    needs: run-ci-coverage
    uses: ./.github/workflows/sonar-analysis.yml

  run-docker-publish:
    needs: run-sonar-analysis
    uses: ./.github/workflows/docker-publish.yml
