name: Orchestrator Workflow

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-ci-sonar:
    uses: ./.github/workflows/ci-sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  run-docker-publish:
    needs: run-ci-sonar
    uses: ./.github/workflows/docker-publish.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
